name: ebook_shop
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  provider: ^5.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dependency_overides:
  url_launcher_web: ^2.0.6

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  assets:
    - assets/Background.jpg
  fonts:
    - family: BebasNeue # Nama font yang akan digunakan dalam Flutter
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf # Path ke file font
          weight: 400
  uses-material-design: true
